### ISSUE TITLE
How to make a clone of server instances. any idea?

### ISSUE THREAD

**Issue by kiran4298** [tfonteyn/profilecloner#10]

**Comment by tfonteyn** [comment]
Unless I misunderstand your question, here is a quote from the read-me. If I did misunderstand, let me know obv.

Examples for "/from=value destinationvalue":
  Domain mode:
    /socket-binding-group=full-ha-sockets full-ha-sockets-copy
    /profile=full-ha full-ha-copy
    /profile=full-ha/subsystem=web web

  Standalone server:
    /subsystem=security security
    profile
   The latter being a shortcut to clone all subsystems in individual batches
