### ISSUE TITLE
JBOSS EAP 6.4.23 Problem with injection of name="default" for some clone results.

### ISSUE THREAD

**Issue by atfrench** [tfonteyn/profilecloner#11]
When cloning an ha profile, for these subsystems noted below, the resulting jbcli in error is:

/profile="ha-adrien"/subsystem="jca"/workmanager="default"/long-running-threads="default":add(core-threads="50",keepalive-time={"time" => "10","unit" => "SECONDS"},max-threads="50",**name="default"**,queue-length="50")

/profile="ha-adrien"/subsystem="jca"/workmanager="default"/short-running-threads="default":add(core-threads="50",keepalive-time={"time" => "10","unit" => "SECONDS"},max-threads="50",**name="default"**,queue-length="50")

/profile="ha-adrien"/subsystem="ejb3"/service="timer-service":add(default-data-store="default-file-store",thread-pool-**name="default"**)

The jboss-cli.sh error for example:
'name' is not found among the supported properties: [thread-factory, queue-length, core-threads, max-threads, handoff-executor, allow-core-timeout, keepalive-time]

Removing name="default" will work with success.

Not sure if this is a problem with the profilecloner or our environment.

Attached the subsystem xml from domain.xml

**Comment by atfrench** [comment]
[jboss subsystems.txt](https://github.com/tfonteyn/profilecloner/files/6904177/jboss.subsystems.txt)

**Comment by tfonteyn** [comment]
likely a couple of years too late for you - I had zero interest in revisiting this project earlier - but today's release fixes this.
